services:
  glacier-verifier:
    image: docker.io/glaciernetwork/glacier-verifier:v0.0.2
    container_name: glacier-verifier
    ports:
      - "10801:10801"
    env_file:
      - .env
    restart: unless-stopped
